name: Publish Maven Package

on:
  push:
    branches: [main, dev]
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'librca'
          java-version: '17'

      - name: Publish to GitHub Packages
        run: mvn deploy --no-transfer-progress
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
